### ISSUE TITLE
How can I use proto files which import another proto files?

### ISSUE THREAD

**Issue by viktorhunko** [NoriSte/cypress-protobuf#3]
Let's say I have two proto files: `example.proto`, `common.proto`. Inside of `common.proto` there is `COMMON_MESSAGE_NAME` message, and this `common.proto` is imported to `example.proto`.

When I'm using `example.proto` I see an error that `COMMON_MESSAGE_NAME` can't be founded

**Comment by NoriSte** [comment]
Hi @viktorhunko 
Do you have a GitHub repo ready to be pulled and used to resolve your issue?

**Comment by NoriSte** [comment]
Hi @viktorhunko 
I've just tried with a project of mine reproducing what you describe with no issues. Could you share a repo with the (at least minimal) configuration needed to reproduce the error you're facing? I'll take a look at that 😉

**Comment by NoriSte** [comment]
@viktorhunko I close the issue due to the inactivity, feel free to re-open it with some more details 👋
